### ISSUE TITLE
KeyError when trying synthesis.py on cmu_arctic

### ISSUE THREAD

**Issue by ricardokleinklein** [r9y9/wavenet_vocoder#10]
Hi,

After successfully running `python preprocess.py cmu_arctic ./../../data/cmu_arctic ./../tmp_cmu_arctic`
and 
`python train.py --data-root=./../tmp_cmu_arctic  --hparams="cin_channels=80,gin_channels=16,n_speakers=7"`

when I try to use synthesis.py, I find the following KeyError when trying to load the model at line 149:

> (wavenet)v-ricardo@gpu14:/work/smg/v-ricardo/EXPERIMENTS/wavenet/wavenet_vocoder$ python synthesis.py ./checkpoints/checkpoint_step000030000.pth ./output_cmu_arctic/
> Using TensorFlow backend.
> Command line args:
>  {'--conditional': None,
>  '--file-name-suffix': '',
>  '--help': False,
>  '--hparams': '',
>  '--initial-value': None,
>  '--length': '32000',
>  '--output-html': False,
>  '--speaker-id': None,
>  '<checkpoint>': './checkpoints/checkpoint_step000030000.pth',
>  '<dst_dir>': './output_cmu_arctic/'}
> Load checkpoint from ./checkpoints/checkpoint_step000030000.pth
> Traceback (most recent call last):
>   File "synthesis.py", line 149, in <module>
>     model.load_state_dict(checkpoint["state_dict"])
>   File "/work/smg/v-ricardo/EXPERIMENTS/wavenet/lib/python3.5/site-packages/torch/nn/modules/module.py", line 490, in load_state_dict
>     .format(name))
> KeyError: 'unexpected key "conv_layers.0.conv1x1g.bias" in state_dict'
> 

has anyone else found this problem before? Or do you know how I can get round it?
There was not problem whatsoever during preprocessing or training.

Thank you!

**Comment by r9y9** [comment]
Did you use the same hyper parameters for training and synshesis?

**Comment by ricardokleinklein** [comment]
No, I didn't. Sorry, a misunderstanding on my side. 
Thank you very much!
