### ISSUE TITLE
ModuleNotFoundError: No module named 'wavenet_vocoder.version'

### ISSUE THREAD

**Issue by youssefsharief** [r9y9/wavenet_vocoder#101]
Thank you for the awesome job

I am getting this error 

> "ModuleNotFoundError: No module named 'wavenet_vocoder.version'"

for the following command:

> python preprocess.py ljspeech ~/data/LJSpeech-1.1 ./data/ljspeech

What I currently did is I added a file called version.py in the wavenet_vocoder folder and I added the following line 

`__version__ = 1.0`

is that fine?

**Comment by r9y9** [comment]
https://github.com/r9y9/wavenet_vocoder#installation Please follow the installation guide. version.py should be generated during installation time. https://github.com/r9y9/wavenet_vocoder/blob/4b438ce9cefda398bd2c1074b8a07f771b44549c/setup.py#L26-L38

**Comment by youssefsharief** [comment]
Thank you so much @r9y9 . Amazing job.
