### ISSUE TITLE
Synthesis for LJ Speech Model

### ISSUE THREAD

**Issue by vijaysumaravi** [r9y9/wavenet_vocoder#102]
When I run the code just for synthesis using the model I downloaded from the link provided, I get the following error: 

Traceback (most recent call last):
  File "synthesis.py", line 204, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 128, in wavegen
    log_scale_min=hparams.log_scale_min)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/wavenet.py", line 335, in incremental_forward
    x, h = f.incremental_forward(x, ct, gt)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/modules.py", line 135, in incremental_forward
    return self._forward(x, c, g, True)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/modules.py", line 166, in _forward
    c = _conv1x1_forward(self.conv1x1c, c, is_incremental)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/modules.py", line 55, in _conv1x1_forward
    x = conv.incremental_forward(x)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/conv.py", line 45, in incremental_forward
    output = F.linear(input.view(bsz, -1), weight, self.bias)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet/lib/python3.5/site-packages/torch/nn/functional.py", line 1024, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [1 x 227], m2: [80 x 512] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

___________________________________________________________________________________________________

My command is: 
python synthesis.py --preset=models/20180510_mixture_lj_checkpoint_step000320000_ema.json --conditional=../singletaco/spectrogram.npy models/20180510_mixture_lj_checkpoint_step000320000_ema.pth generate/

Spectrogramp.npy is 80x227

Any help is appreciated. Thanks!

**Comment by r9y9** [comment]
> RuntimeError: size mismatch, m1: [1 x 227], m2: [80 x 512] at 

I think this should be m1: [1 x 80], m2: [80 x 512]. So try swapping your mel-spectrogram?

**Comment by vijaysumaravi** [comment]
When I do that I get this:

Traceback (most recent call last):
  File "synthesis.py", line 205, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 131, in wavegen
    log_scale_min=hparams.log_scale_min)
  File "/home/vijay/speech_tts/wavenet_vocoder/wavenet_vocoder/wavenet.py", line 304, in incremental_forward
    assert c.size(-1) == T
AssertionError

**Comment by r9y9** [comment]
Not sure where you inserted swapping but this is what I have locally:

```
In [1]: import numpy as np

In [2]: np.load("./data/ljspeech/ljspeech-mel-00001.npy").shape
Out[2]: (835, 80)
```

and 

```
python synthesis.py 20180510_mixture_lj_checkpoint_step000320000_ema.pth generated\
 --conditional=./data/ljspeech/ljspeech-mel-00001.npy \
 --preset=./20180510_mixture_lj_checkpoint_step000320000_ema.json
```

it works for me.

**Comment by vijaysumaravi** [comment]
Thank you so much! That worked! I was swapping the spectrogram after passing it to the synthesis function. When I pass the swapped numpy file, it works fine.  

I am now able to generate the .wav file but when I listen to it, it is nothing but silence! Any idea why this could be happening?

**Comment by vijaysumaravi** [comment]
This is the command line output. 


python synthesis.py --preset=models/20180510_mixture_lj_checkpoint_step000320000_ema.json --conditional=../singletaco/spectrogram.npy models/20180510_mixture_lj_checkpoint_step000320000_ema.pth generate/
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Command line args:
 {'--conditional': '../singletaco/spectrogram.npy',
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--initial-value': None,
 '--length': '32000',
 '--max-abs-value': '-1',
 '--output-html': False,
 '--preset': 'models/20180510_mixture_lj_checkpoint_step000320000_ema.json',
 '--speaker-id': None,
 '--symmetric-mels': False,
 '<checkpoint>': 'models/20180510_mixture_lj_checkpoint_step000320000_ema.pth',
 '<dst_dir>': 'generate/'}
Load checkpoint from models/20180510_mixture_lj_checkpoint_step000320000_ema.pth
  0%|                                                             | 0/55552 [00:00<?, ?it/s]/home/vijay/speech_tts/wavenet_vocoder/wavenet/lib/python3.5/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/home/vijay/speech_tts/wavenet_vocoder/wavenet/lib/python3.5/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
 13%|██████▍                                          | 7237/55552 [01:03<07:04, 113.86it/s] 14%|███████                                          | 8053/55552 [01:10<06:56, 113.99it/s] 15%|███████▏                                         | 8137/55552 [01:11<06:55, 114.01it/s] 15%|███████▎                                         | 8221/55552 [01:12<06:55, 114.02it/s]100%|████████████████████████████████████████████████| 55552/55552 [08:02<00:00, 115.03it/s]
Finished! Check out generate/ for generated audio samples

**Comment by blacksph3re** [comment]
I had the same problem in the setup and I found that the spectograms from tacotron aren't normalized. Try normalizing them, for me it worked fine then

**Comment by r9y9** [comment]
Well, then https://github.com/NVIDIA/tacotron2/issues/40, https://github.com/NVIDIA/tacotron2/issues/24, https://github.com/NVIDIA/tacotron2/issues/52 might help.

**Comment by vijaysumaravi** [comment]
Thank you so much! It is now working.
