### ISSUE TITLE
Recent versions works in save_states (audio), but white noise in fast eval_model(train_eval)

### ISSUE THREAD

**Issue by engiecat** [r9y9/wavenet_vocoder#106]
Hello.

I am currently experiencing very  strange behaviors after updating from https://github.com/r9y9/wavenet_vocoder/commit/2b557d4cbacef52bc3441fc4f2c54b1351ae9df4 to current https://github.com/r9y9/wavenet_vocoder/commit/7c87267f2c53d2dd54cdb35157607a50053a7f69
while training multispeaker version of the wavenet. (didn't try single speaker yet)

### Symptoms ###
A. While samples generated with save_states are working, the train_eval files generated in eval_model is white noise.
![step000030000_waveplots](https://user-images.githubusercontent.com/13521426/44123997-e036e0c2-a065-11e8-992e-178c1b0b8650.png)

B. In synthesis.py, when fast mode is disabled and ema is not used (load checkpoint_blahblah.pth instead of _ema.pth), the generated data is okay. Otherwise, if fast mode is enabled or _ema checkpoint is loaded, the symptom is replicated.
![image](https://user-images.githubusercontent.com/13521426/44124137-9ed12560-a066-11e8-85b8-4cb6b9445960.png)
(above: original snippet(which is extracted from training set), 
middle: synthesized. no fast, no ema, 
bottom: synthesized. fast or ema (both have the same abnormal form))
Note. This is not trained much(30k with batch_size=4), which is why middle one has some discrepancies.

C. Previously trained models are generated fine with synthesis.py regardless of fast mode and ema

### Possible Reasons ###
~~A. Pytorch version had been updated from 0.4.0 to 0.4.1~~
When reverted to https://github.com/r9y9/wavenet_vocoder/commit/2b557d4cbacef52bc3441fc4f2c54b1351ae9df4 , this works well even on PyTorch 0.4.1 and the synthesis.py result is quickly restored to its normal form (after 400 steps from the previous faulty checkpoint)
![step000040000_waveplots](https://user-images.githubusercontent.com/13521426/44129296-8930f7fa-a082-11e8-9bb2-539c05e7a342.png)

~~B. Environment had been changed from Windows to Ubuntu while workaround for #63 was applied.
(See https://github.com/engiecat/wavenet_vocoder/commit/1990e2f998d7b5c3642a77f943c4c18d6de65217 )~~
~~Other works had been done on my repos, but it was limited to data preprocessing,~~
Tested with https://github.com/r9y9/wavenet_vocoder/commit/7c87267f2c53d2dd54cdb35157607a50053a7f69 but still persists

**Comment by r9y9** [comment]
Thank you for the detailed report. Very helpful as always! I would like to investigate it too, but currently I have a lot of things to do (off topic though, I'm moving to South Korea from Japan next month). I will look into it once I get a chance.

**Comment by engiecat** [comment]
I will also look at the issue when I get some time :)

(off topic - South Korea is really nice in September! (especially mountains and fields are exquisite) )

**Comment by jseplae** [comment]
I believe I'm experiencing something similiar (PyTorch 0.4.1) as described here. The results in the "audio" folder seem OK, but "test_eval" and "train_eval" both contain garbage at 60k steps.

**Comment by r9y9** [comment]
garbage at 60k should be fine. Results in "audio" should always better because it uses teacher-forcing, while train_eval/test_eval uses sampling.
