### ISSUE TITLE
is this right link of the pretrained model 1000k?

### ISSUE THREAD

**Issue by Yeongtae** [r9y9/wavenet_vocoder#107]
@r9y9 
![image](https://user-images.githubusercontent.com/13597229/44248472-a9bc9c00-a225-11e8-8994-a9559e555d35.png)
Using above link, I could get bellow pretrained model.
![image](https://user-images.githubusercontent.com/13597229/44256096-0ed2ba80-a243-11e8-85fb-b3ce314ae4be.png)
- It seems to be not 100K.

I have run synthesize.py using the pretrained model at the above image. 
But I could get a noisy wav file.

[0817.zip](https://github.com/r9y9/wavenet_vocoder/files/2296021/0817.zip)

The wavs with prefix 'wav-*' are generated by using https://github.com/Rayhane-mamah/Tacotron-2 with your pretrained model
A wav with prefix '20180510_*' is generated by using above pretrained model.

Please check above link.

**Comment by r9y9** [comment]
Have you checked https://github.com/r9y9/wavenet_vocoder#online-tts-demo? Let me know if it doesn't work.

**Comment by r9y9** [comment]
> It seems to be not 100K.

This is because I trained the model multiple times from step 0. Approx 300k * 4 > 1000k..

**Comment by Rayhane-mamah** [comment]
Hello, pardon me intruding here :)

@Yeongtae you don't seem to be rescaling T2 output mels to [0, 1] @r9y9's demo shows how to do that correctly. I'm out of here :)

**Comment by r9y9** [comment]
I'm closing this. Feel free to reopen if the problem persists.
