### ISSUE TITLE
Unable to generate good sound with pretrained model

### ISSUE THREAD

**Issue by skyw** [r9y9/wavenet_vocoder#108]
I downloaded 20180212_mixture_multispeaker_cmu_arctic_checkpoint_step000740000_ema.pth

And tried to synthesis with cmd line
python synthesis.py 20180212_mixture_multispeaker_cmu_arctic_checkpoint_step000740000_ema.pth ./ --preset=20180212_multispeaker_cmu_arctic_mixture.json --speaker-id 1 --hparams="sample_rate=16000" --conditional=cmu_arctic/cmu_arctic-mel-00001.npy

The sound quality is way worse than what's on the demo page. Is my cmd line correct?
I did search issues, but couldn't find the answer. There is one issues says sample_rate=16000 was the problem. But it doesn't work for me.

**Comment by r9y9** [comment]
I think it's correct. Guess two things:

- Did you run `git checkout b1a1076`?
- With that specific commit and the hyper parameters, did you rerun the preprocessing?

**Comment by skyw** [comment]
I didn't.
Checking out the right commit seems to fix it. I thought it was fine to use latest code as it doesn't pop any error. thanks.

**Comment by zctang** [comment]
@skyw  Hi, skyw did you generate good sound with pretrained model after you run git checkout b1a1076 and rerun the preprocessing? I also unable to generate good sound. thank you
