### ISSUE TITLE
Quick Feedback

### ISSUE THREAD

**Issue by imdatsolak** [r9y9/wavenet_vocoder#11]
Hi, @r9y9, I have been training few models the last couple of days with wavenet_vocoder and I must say the results are impressive.

Here are some learning charts:
![screen shot 2018-01-29 at 16 46 41](https://user-images.githubusercontent.com/10852644/35519334-39b8c220-0514-11e8-8a3c-5699228f4813.png)
![screen shot 2018-01-29 at 16 46 48](https://user-images.githubusercontent.com/10852644/35519337-3e703a50-0514-11e8-9bb7-b4954d504a73.png)

The blue line represents learning with 24 layers, 4 stacks
The red line is 40 layers, 4 stacks.
I have also waveplots for both.
24 layers, 4 stacks:
![step000255024_waveplots](https://user-images.githubusercontent.com/10852644/35519413-6db27652-0514-11e8-942b-36ba09ae7695.png)

40 layers, 4 stacks:
![step000176640_waveplots](https://user-images.githubusercontent.com/10852644/35519430-7dbc44d8-0514-11e8-89f1-f81528428100.png)

My data is roughly five hours total training data (split into training and testing). The audio results are quite impressive after already 140k steps; currently testing with 250k steps (24 layers, 4 stacks).

At one point, I will (hopefully) be able to test it with 65k quantization instead of 256, provided it fits into my GPUs RAM. 
Since I have a few 1080 Ti, I can train multiple models in parallel and the training is super-efficient (100% GPU-utilization) and very, very fast. 
What I would like to do is parallel-training (on multiple GPUs) as well as (later on) parallel prediction.

The major task for me is to integrate your Vocoder into [Tacotron-2](https://github.com/Rayhane-mamah/Tacotron-2/tree/master/tacotron) - hopefully I can show something towards end of February. The other project is generating music, but that is just a side project.

Again, thanks for such a great work and if you have any pointers regarding multi-GPU-training, it would be appreciated...

**Comment by r9y9** [comment]
Hi, thank you for your feedback. I am happy to hear that my project helps you.  As for the multi-GPU training, I'm afraid that I have no experience on it until now. I will get one more GTX 1080 Ti next month and try distributed training if I get a chance. I look forward to seeing progress on your Tactoron2 project!

**Comment by imdatsolak** [comment]
Hi @r9y9, when I set "cin_" to "-1" in order to train without conditioning, I get multiple errors (in train.py:411 and later on also in wavenet.py:168) because they expect "c" to contain the conditioning features. I would like to test music generation without conditioning, any ideas to fix these?

Thanks

**Comment by r9y9** [comment]
Sorry about that. Will look into it.

**Comment by r9y9** [comment]
Should be fixed at https://github.com/r9y9/wavenet_vocoder/commit/c68767f117f64d96606a92ae4d69e909e204f836

**Comment by imdatsolak** [comment]
Thank you very much, very, very appreciated 👍

**Comment by gsoul** [comment]
@r9y9 thank you for your excellent code. As for multi-gpu training, it seems like TF simplified it a bit in their latest release: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/estimator/python/estimator/replicate_model_fn.py

**Comment by imdatsolak** [comment]
@gsoul, since wavenet_vocoder is in PyTorch (@r9y9 is only using tf for tensorboard-support), and as there is actually kind of easy support in PyTorch for DataParallel, we need to get the hooks right in wavenet_vocoder. I'm currently evaluating where best to put to hook into and (if I have a solution), I'll send a PR to @r9y9 ...

**Comment by gsoul** [comment]
Oh mine, that was stupid of me, my apologies.

**Comment by imdatsolak** [comment]
@r9y9, @gsoul, looking through the code (wavenet_vocoder as well as PyTorch source code), the only change needed _seems_ to be (in train.py):

    model = build_model()
    print(model)
    model = torch.nn.DataParallel(model)

Would you agree?

**Comment by r9y9** [comment]
Looking through the pytorch example, we may need to adjust sampler as well.  
 https://github.com/pytorch/examples/blob/963f7d1777cd20af3be30df40633356ba82a6b0c/imagenet/main.py#L128-L131

**Comment by imdatsolak** [comment]
Thanks, @r9y9, will look into it...
