### ISSUE TITLE
Good Work,  trained with LJSpeech and 23 hours, 

### ISSUE THREAD

**Issue by icewwn** [r9y9/wavenet_vocoder#110]
Amazing work, trained with LJSpeech on 1070 Ti in 23 hours, 
I got the good synthesized samples on ground truth 

Above is recordings,
Below is synthesized by synthesis.py with ground truth.
Sound good except end noise on silence segment.  

![samples](https://user-images.githubusercontent.com/2451339/45253670-953f6f80-b39d-11e8-8d59-56af428f73dd.png)

**Comment by r9y9** [comment]
Hi, thanks. I think you just need to be patient. From my experience, it usually requires more than 1000k steps (~2 weeks on a single 1080Ti) to get noise-less high-quality synthetic speech.
