### ISSUE TITLE
How speed up the Wavenet synthesis？

### ISSUE THREAD

**Issue by peter05010402** [r9y9/wavenet_vocoder#113]
Hello @r9y9 ，
I found the size of raw wav file can influence the restore PR speed .
if the raw size is more than 600k, the synthesis time cost 1.5hours.
Could give some suggestion to improve it?

**Comment by hcwu1993** [comment]
WaveNet synthesis is sample by sample, time cost is times of raw size. you can the paper parallel wavenet, it can speed up.

**Comment by peter05010402** [comment]
@hcwu1993 Thank  you for reply!
When synthesis is being, the GPU memory is only used 1271MB, but the full memory is 16GB
![99999](https://user-images.githubusercontent.com/42974031/45544059-dc6bab80-b848-11e8-8e37-e1b14d0600dd.JPG)

if WaveNet use more GPU memory , Maybe less time cost?

**Comment by hcwu1993** [comment]
@peter05010402 That's a good idea. Maybe you can see the nvidia implementation, nv-wavenet.

**Comment by tomse-h** [comment]
Did anyone figure out, how to make the inference use more GPU memory yet? If so, did it speed up the process?

**Comment by r9y9** [comment]
I'm not sure why you expect inference speedup by just increasing GPU memory usage. Generating multiple utterances at once could improve time per utterance though.

**Comment by fatchord** [comment]
@r9y9 Batched inference works quite well with WaveRNN - only a small drop in sound quality - I see no reason why it wouldn't work for Wavenet. You can expect around a 10x or more speedup and it's pretty easy to implement. https://github.com/fatchord/WaveRNN/issues/9#issuecomment-444935577

**Comment by r9y9** [comment]
@fatchord Thanks for letting me know.  Yes, I think that would work for WaveNet as well. 10x or more speedup is pretty nice:)

**Comment by Rajdeep97** [comment]
Can someone please explain, it takes us up to 20 mins to synthesize one line(Google Colab GPU) . How can Google do it in milliseconds?

**Comment by SergeiNarozhnyi** [comment]
Second @Rajdeep97 for desired explanation :)

**Comment by japita-se** [comment]
Does anybody know how to speedup synthesis? It takes 40 seconds on my laptop with Geoforce GTX 950M

**Comment by r9y9** [comment]
Several ways:

- Implement parallel wavenet or similar (https://github.com/ksw0306/ClariNet will be a good start though the speech quality is not convincing IMO)
- Generate multiple utterances at the same time (batch generation)

For the latter one, I'm going to support it soon (I have it locally). Should be addressed when I work for #157.
