### ISSUE TITLE
How low can the loss be?

### ISSUE THREAD

**Issue by UESTCgan** [r9y9/wavenet_vocoder#115]
I train it on the data of Ljspeech. After trained over 600k, the loss decrease slowly. I want to know how low can the loss be.

![image](https://user-images.githubusercontent.com/40649244/45743472-ac4c5000-bc2e-11e8-999b-39289955b061.png)

@r9y9 How much is the loss of your mode  (20180510_mixture_lj_checkpoint_step000320000_ema.pth) ?

**Comment by UESTCgan** [comment]
@begeekmyfriend

**Comment by begeekmyfriend** [comment]
Roughly speaking it depends on your corpus... As for me, it is roughly 5.5.

**Comment by UESTCgan** [comment]
@begeekmyfriend Ok，I understand.Thanks for your reply. I know the extent of loss.I find that much of our work is the same as yours. Looking forward to more communication with you.Thanks again !
