### ISSUE TITLE
possible to mimic new voices without full training?

### ISSUE THREAD

**Issue by hrbigelow** [r9y9/wavenet_vocoder#116]
The way WaveNet is set up, different speakers in the training dataset are identified by an ID, and WaveNet learns an embedding for the ID and then uses this as a global condition.  This means a trained WaveNet model is only capable of synthesizing from one of these voices.  Is there any way to enable WaveNet to mimic a totally new voice, without first collecting data and from that voice and training it?

I know this is a broad reaearch question but figured people here may have thought about it.

I'm thinking perhaps there is a computationally cheap way to collect some summary statistics from a smaller sample of the new voice, and use that as a condition.  No idea what that would be, but this is just a first thought.

**Comment by alexdemartos** [comment]
Have a look at this:

https://arxiv.org/abs/1806.04558
