### ISSUE TITLE
Ask about Phoneme Segmentation and Phoneme Duration

### ISSUE THREAD

**Issue by toannhu** [r9y9/wavenet_vocoder#12]
Hi, @r9y9. First of all, thank you for such a brilliant implementation of Wavenet. Now I study about how to detect a phoneme duration (start time and end time of phoneme) extracted from audio and align this thing with linguistic feature but i don't know how to do this. Can you show me the idea that you use to solve the problem and where is the code in this repo to do this job? Thanks!

![1](https://user-images.githubusercontent.com/19307982/35554382-19eb4606-05ce-11e8-9a2c-693b0381dfa0.png)

P/s: Btw is this possible to train this repo with another language? Currently, I'm doing with Vietnamese with my own dataset (7 hours of audio and ARPABET linguistic feature extracted from text)

**Comment by r9y9** [comment]
The repository focuses on the WaveNet vocoder as the name says. It doesn't provide any of phoneme duration estimation and linguistic features extraction, which are needed to replicate original WaveNet-based TTS. The vocoder can take arbitrary type of input assuming time resolution is adjusted, though.

Linguistic feature extraction (a.k.a text processing frontend) is the hard part of TTS, which often requires deep knowledge for the target language. The WaveNet vocoder itself is language independent but you will have to  implement a text processing frontend if you want to condition the model by linguistic features.

**Comment by toannhu** [comment]
@r9y9 @imdatsolak Thanks for support. I have found [Montreal Forced Aligner Tool](http://montreal-forced-aligner.readthedocs.io) that help me with this problem. As I see in this repo, @r9y9 uses another library [nnmnkwii](https://github.com/r9y9/nnmnkwii) to do the frontend things. Please excuse my ignorance but can you explain for me what the input feed to Wavenet vocoder for local condition? It's very helpful to know the basic ideas about how Wavenet vocoder works. I'm really confused when read this repo's code. Once again thank you!

**Comment by r9y9** [comment]
There's no text processing frontend used in the repository. nnmnkwii has functionality to extract linguistic features from HTS-style context labels, though. In this repository nnmnkwii is used for mostly preprocesssing. e.g, mulaw or inv_mulaw. https://r9y9.github.io/nnmnkwii/latest/references/preprocessing.html

The `WaveNet` class in the repository doesn't assume any particular domain of the conditional features, but training / pre-processing scripts are written assuming mel-spectrogram is used for the conditional feature.

**Comment by toannhu** [comment]
@r9y9 Thanks for enlight me. Finally I got the key thing. One more question, is this possible to use Wavenet Vocoder with Tacotron? Do you plan to this thing in the future? Any idea suggestion?

**Comment by r9y9** [comment]
Definitely it's possible. Tacotron2-like wavenet vocoder is WIP at https://github.com/r9y9/deepvoice3_pytorch/pull/21.

See also https://github.com/r9y9/wavenet_vocoder/issues/1#issuecomment-359182424.

**Comment by r9y9** [comment]
Taoctron + WaveNet was done

**Comment by toannhu** [comment]
@r9y9 Thanks. I succeed in training Rayhane-mamah's Tacotron 2 repo with my own corpus. Going to try out generate with your WaveNet Vocoder. I'm eager to hear the result. This makes me very exciting!

**Comment by toannhu** [comment]
@r9y9 I tried to intergrate Rayhane-mamah's Tacotron 2 with WaveNet Vocoder using your Google Colab's code but it failed. The pitch has been lost. Btw, I use `batch_size = 16` and `r=2` in Tacotron 2 and `batch_size = 1` in your repo. Wavenet Repo is training with original sound not with GTA. Here are the results.
[sound.zip](https://github.com/r9y9/wavenet_vocoder/files/2042470/sound.zip)
