### ISSUE TITLE
synthesize from text

### ISSUE THREAD

**Issue by ramilrg** [r9y9/wavenet_vocoder#125]
Hi,
is it possible/available to synthesize voice from directly text input or it is available in another your project  [https://github.com/r9y9/deepvoice3_pytorch](url) ?

Thanks

**Comment by r9y9** [comment]
https://github.com/r9y9/wavenet_vocoder#pre-trained-models

> Note: This is not itself a text-to-speech (TTS) model. With a pre-trained model provided here, you can synthesize waveform given a mel spectrogram, not raw text. You will need mel-spectrogram prediction model (such as Tacotron2) to use the pre-trained models for TTS.

Please read the REAEME.

**Comment by Shridharpawar77** [comment]
Hi r9y9,
I am trying to provide mel-spectrograms obtained from decoders of deepvoice3 as input to wavenet vocoder in synthesis.py  but I am not getting good results. Is there any preprocessing  required to generate good results.
