### ISSUE TITLE
Can not reproduce the good effect as shown in the pretrained 20180510_mixture_lj_checkpoint_step000320000_ema.pth

### ISSUE THREAD

**Issue by hxs7709** [r9y9/wavenet_vocoder#129]
hello, all:

I can not reproduce the good effect as shown in the pretrained 20180510_mixture_lj_checkpoint_step000320000_ema.pth. Please help to review and give me clue about it. Thank you very much.

From the following link, the pretrained Tact2 (189.5k steps) and wavenet (320k steps)  model can synthesis good audio.  https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb
My synthesized file is like this: 
[From__Tacotron2_and_WaveNet_text_to_speech_demo_ipynb(Tact200k+WNr9y9Pretrained320k).wav.zip](https://github.com/r9y9/wavenet_vocoder/files/2537910/From__Tacotron2_and_WaveNet_text_to_speech_demo_ipynb.Tact200k%2BWNr9y9Pretrained320k.wav.zip)

But when I train to get wavenet model with following settings. My synthesis audio on the training steps even 510k is bad, like this.
[From__Tacotron2_and_WaveNet_text_to_speech_demo_ipynb(Tact200k+WNEricTrained510k).wav.zip](https://github.com/r9y9/wavenet_vocoder/files/2537922/From__Tacotron2_and_WaveNet_text_to_speech_demo_ipynb.Tact200k%2BWNEricTrained510k.wav.zip)

**Comment by hxs7709** [comment]
I train to get wavenet model with following settings.
It is expected to get the similar effect as the pretrained 20180510_mixture_lj_checkpoint_step000320000_ema.pth. But it does not happen even the models is from 510k training steps in my training.
Please help to show any clue or suggestion for further research.
Anyway, I will continue to train for more than 100k steps, and then check the result.
Thank you.

1. Get latest code on 2018.10.24 from https://github.com/r9y9/wavenet_vocoder

2. Use the 1.1 version ljspeech from https://keithito.com/LJ-Speech-Dataset/

3. Preprocess with the same parameters from 20180510_mixture_lj_checkpoint_step000320000_ema.json:

python preprocess.py ljspeech LJSpeech-1.1 ljspeech_preprocess --preset=./20180510_mixture_lj_checkpoint_step000320000_ema.json

4. Train with the same parameters from 20180510_mixture_lj_checkpoint_step000320000_ema.json:

python train.py --data-root=ljspeech_preprocess --preset=./20180510_mixture_lj_checkpoint_step000320000_ema.json

**Comment by r9y9** [comment]
Please see https://github.com/r9y9/wavenet_vocoder/commit/47064d58275af2e46a4efdab3121b7a835af9003.

**Comment by hxs7709** [comment]
Thank you very much for your great work and quick answer.
I will check the related suggestion in issues and continue to train for more than 100k steps and evaluate it. 

PS: 
The 320000 in the model name "20180510_mixture_lj_checkpoint_step000320000_ema.pth" misguide me. Actually the pretrain-ed model is trained for more than 1000k steps in total.

**Comment by hxs7709** [comment]
The synthesized wav on 970k step is already natural and with little flaw (refer to attached below), so close this issue. Thank you.
[wavenet_vocoder_1024branch_r9y9_ljspeech--970k.zip](https://github.com/r9y9/wavenet_vocoder/files/2598512/wavenet_vocoder_1024branch_r9y9_ljspeech--970k.zip)
