### ISSUE TITLE
Music generation

### ISSUE THREAD

**Issue by r9y9** [r9y9/wavenet_vocoder#13]
Things I want to try if I get a chance, Comments and requests are welcome.
 
- [ ] Music generation (unconditional)
- [ ] MIDI-conditioned piano sound generation

**Comment by imdatsolak** [comment]
@r9y9, I've started training a model on Beethoven piano concertos.
Learnings: use only data that has the same tempo (e.g. "Adagio only"). 
Don't use too much data (I have about 20 minutes)
Use only single-instrument music.

Hope that helps. Initial results are not very promising so far. I only used "Click Remover" and "Amplify" on top of what wavenet_vocoder generated.

 I would love to use 65536 quantizations, but my GPU-memory is not enough (11GB).

**Comment by r9y9** [comment]
With mixture of logistic distributions, we can reduce GPU-memory usage drastically. For example, with 10 mixture of logistic distributions, we have only 30 nodes in the output layer. 

https://github.com/r9y9/wavenet_vocoder/blob/3cf66f5a6b0df55bca98fe4967f5bb2ca2fcb86d/hparams.py#L60-L62

One drawback of use of logistic distributions I noticed from my experiments is that it will take too much time (7 ~ 10 days) to get sufficient good quality of generated speech.

**Comment by imdatsolak** [comment]
Currently, I'm using `out_channels = 256` because `quantize_channels=256` and `input_type=mulaw-quantize`.

Even with these settings, it takes quite some time to generate music. wavenet is computationally quite intensive (as you well know). I'm looking into areas where we can make it faster...
