### ISSUE TITLE
Bug in PartialyRandomizedSimilarTimeLengthSampler(Sampler) ??

### ISSUE THREAD

**Issue by echoaimaomao** [r9y9/wavenet_vocoder#130]
I think class PartialyRandomizedSimilarTimeLengthSampler(Sampler) is used to generate shuffled indices. However, I had found that the code "random.shuffle(indices[s:e])" do not shuffle the values in indices correctly. Many repeat values existed. I had no idea about it. However, if I  changed the indices type from tensor to numpy, and then changed the type from numpy back to tensor after  the indices is shuffled. 
Here is the dedugging in the code, the orginal indices and once shuffled indices, batch_group_size = 64. Many repeated values in the first 64 values.

![_20181115205825](https://user-images.githubusercontent.com/8649753/48554674-fe9daa80-e919-11e8-9779-0f2db74f3a6d.jpg)

**Comment by r9y9** [comment]
I had a chance to look into it and am seeing a weird behavior for the shuffle operations. 

This is why fetchord write a sampler like this: https://github.com/fatchord/WaveRNN/blob/3cd8c93920197759d6ee9315381f30d9733f71ad/utils/dataset.py#L197-L198. It is indeed very similar to my sampler. Thank you very much for raising the issue. I will update the code accordingly.

**Comment by r9y9** [comment]
Sorry to be super late, @echoaimaomao, but thank you very much! I added an assertion to make sure we no longer have the same bug, but feel free to reopen if you still see the problem.

side note: I originally wrote the sampler for training end-to-end models (e.g. Tacotron, Deep Voice3) where the batch size and masking loss matter a lot. Perhaps we can safely remove the sampler for WaveNet, but I will keep the code as is.

**Comment by echoaimaomao** [comment]
Thank you very much for sharing your code. It does benefit my work during my Phd.  You are the sunshine~~~☺
