### ISSUE TITLE
Possible to produce good quality unconditional speech?

### ISSUE THREAD

**Issue by realtimecrime** [r9y9/wavenet_vocoder#138]
Hi, 
many thanks for this great project.
I am trying to reproduce unconditional speech samples. Is it possible to achieve good sound quality (comparable to the samples provided by google's wavenet) without conditioning on mel spectrograms with this code? I am training a model without local and global conditioning right now, but so far (160k steps) it only produces noise.

**Comment by r9y9** [comment]
Not sure if it helps, but you can find some samples at https://github.com/r9y9/wavenet_vocoder/issues/1#issuecomment-354586299.
