### ISSUE TITLE
Hi,is there any proof for  how discretized_mix_logistic_loss works? 

### ISSUE THREAD

**Issue by jiqizaisikao** [r9y9/wavenet_vocoder#14]
Hi:
I read the paper that P(x|π,µ,s) as   discretized mix logistic distributions,and i read the code of pixelcnn++ and yours but i still  not very clear why it written like this,In fact i donot know In pixelcnn++ what is the coeffs var represent and why it is removed in your code?
is there any mathematical proof for this?

**Comment by azraelkuan** [comment]
I have test the discretized mix logistic distributions in this repository, it works well. for the coeffs, it is the reason that the image has two channels, but the audio only have one , so r9y9 remove it. u can see https://github.com/pclucas14/pixel-cnn-pp/blob/60aa78e0ef1abd54cb87963678fc3d5f0517b5eb/utils.py#L102

**Comment by xfwu** [comment]
Really don't understand why it is needed to change logistic's pdf to cdf (which is sigmoid)... can't it be estimated directly by using pdf?
