### ISSUE TITLE
Reduce background noise to match Google quality?

### ISSUE THREAD

**Issue by duvtedudug** [r9y9/wavenet_vocoder#140]
While quality is good on a highly trained models for RayhaneTaco + r9y9WaveNet combo. I'm finding background hiss/noise performance has plateaued even with further training.

Any methods to try to get this down to Google quality?

Does moving to Ground-truth-aligned Mel specs help this?

**Comment by r9y9** [comment]
This is actually one of the things that I am trying to fix but not yet getting a clear solution.
