### ISSUE TITLE
pretrained ljspeech model are all 13100 files used in training?

### ISSUE THREAD

**Issue by soumimaiti** [r9y9/wavenet_vocoder#144]
Hi,

I wanted to know if all LJspeech files are used for training the pretrained ljspeech model?

I want to fine-tune the model, so I wanted to use the same training files for the fine-tuning.

**Comment by r9y9** [comment]
https://github.com/r9y9/wavenet_vocoder/blob/44e0e361bc02b3e20eb1db4fc5c1c8c04ba01da2/presets/ljspeech_mixture.json#L42

https://github.com/r9y9/wavenet_vocoder/blob/44e0e361bc02b3e20eb1db4fc5c1c8c04ba01da2/train.py#L113-L121

Roughly 4.4% of data was excluded for training.
