### ISSUE TITLE
Tacotron-2 synthesis.py cannot synthesize text

### ISSUE THREAD

**Issue by popo0293** [r9y9/wavenet_vocoder#145]
My work around is to downgrade numpy to 1.14.0 and then it works fine. (May not be the best solution.)
Maybe update dependency?

wavenet training requires numpy 1.16.0
but after one gets the trained model, a lower version is required (because of recent update?)

If you cannot reproduce this error in your online demo, it may already be fixed by the dependent packages' authors.

**Comment by r9y9** [comment]
Ideally, it should work on numpy 1.16.0 too. I tentatively fixed the demo notebook to use numpy < 1.16 because that was the easiest fix for me (see https://github.com/r9y9/Colaboratory/commit/d83d15bd87bbe1b6fbecab302cb7b60b3294dc6e). If you have another fix, I am happy to accept that as a PR.

**Comment by nathphoenix** [comment]
please can you guys help out, i can't even preprocess my data, let alone train
