### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1,513) (0,) 

### ISSUE THREAD

**Issue by Eurus-Holmes** [r9y9/wavenet_vocoder#146]
When running [Online TTS demo](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb) on colab,

ValueError: operands could not be broadcast together with shapes (1,513) (0,) 

<img width="868" alt="屏幕快照 2019-04-15 下午2 44 53" src="https://user-images.githubusercontent.com/34226570/56112266-16429300-5f8d-11e9-9665-84eccd7525e2.png">

**Comment by jybaek** [comment]
it's a library bug. try to use the librosa version `0.6.2` or higher.

**Comment by Eurus-Holmes** [comment]
@jybaek Thanks for your reply! But the ValueError occurred after running
 
```
# Remove old files if exist
! rm -rf tacotron_output
! python synthesize.py --model='Tacotron' --mode='eval' \
  --hparams='symmetric_mels=False,max_abs_value=4.0,power=1.1,outputs_per_step=1' \
  --text_list=./text_list.txt
```

and...how can I update the librosa version on colab...

**Comment by jybaek** [comment]
```
! pip install -U librosa==0.6.2
```

and your `ValueError` is must be open a new issue. more detail.

**Comment by Eurus-Holmes** [comment]
@jybaek hi, thanks for your help, I have updated the librosa version.
And, I have also opened a new issue for more details.
