### ISSUE TITLE
preprocess: errors when "import lws" 

### ISSUE THREAD

**Issue by MorganCZY** [r9y9/wavenet_vocoder#149]
![image](https://user-images.githubusercontent.com/33675916/56417253-e3b6d400-62c5-11e9-8468-c0c08039e3e8.png)
I've installed lws when doing "pip install -e ".[train]"". However, the module "lws" cannot be imported with errors shown in above picture. How can I fix this error?

**Comment by GloomyGhost-MosquitoCoil** [comment]
这个是由你的py环境里的重复引用包引起的，可能你的环境里有2个不同版本的包（比如numpy）导致了引用错误，pip list检查一下

This is caused by a duplicate reference package in your py environment. There may be two different versions of the package (such as numpy) in your environment that cause a reference error. Check the pip list.

これはあなたのpy環境で重複した参照パッケージが原因です。 ご使用の環境には、参照エラーを引き起こす2つの異なるバージョンのパッケージ（numpyなど）があります。 ピップリストを確認してください。

**Comment by r9y9** [comment]
Seems like this is not a problem of our code. Please file an issue at https://github.com/Jonathan-LeRoux/lws.

**Comment by MorganCZY** [comment]
> 这个是由你的py环境里的重复引用包引起的，可能你的环境里有2个不同版本的包（比如numpy）导致了引用错误，pip list检查一下
> 
> This is caused by a duplicate reference package in your py environment. There may be two different versions of the package (such as numpy) in your environment that cause a reference error. Check the pip list.
> 
> これはあなたのpy環境で重複した参照パッケージが原因です。 ご使用の環境には、参照エラーを引き起こす2つの異なるバージョンのパッケージ（numpyなど）があります。 ピップリストを確認してください。
![piplist](https://user-images.githubusercontent.com/33675916/56453682-96476f00-6378-11e9-802d-f172c862c0e3.png)
Here are the details after "pip list". I didn't get a duplicate reference package.

**Comment by r9y9** [comment]
See also https://stackoverflow.com/questions/36190757/numpy-undefined-symbol-pyfpe-jbuf

**Comment by GloomyGhost-MosquitoCoil** [comment]
This is also the case today. My solution is
```
pip uninstall numpy
pip uninstall numpy
pip install numpy
```
Plz do`pip uninstall numpy` Twice

**Comment by GloomyGhost-MosquitoCoil** [comment]
For some reason, pip seems to only show the latest packages, not all

**Comment by MorganCZY** [comment]
Thank you all. My issue has been fixed. I did have some duplicate reference packages. But I just reinstalled lws in version 1.0 to replace version 1.3, then it works.
