### ISSUE TITLE
error in synthesis

### ISSUE THREAD

**Issue by dongmh** [r9y9/wavenet_vocoder#15]
Traceback (most recent call last):
  File "synthesis.py", line 181, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 84, in wavegen
    assert c.ndim == 2
AssertionError

**Comment by r9y9** [comment]
Please provide us more detailed information. What command are you trying? What the full output of the command?

**Comment by dongmh** [comment]
This is the full command and output. Is there anything wrong? Thank you.

$ python synthesis.py ./checkpoints/checkpoint_step000210000.pth ./mytest --conditional=./data/LJSProcessed/ljspeech-audio-00002.npy
Using TensorFlow backend.
Command line args:
 {'--conditional': './data/LJSProcessed/ljspeech-audio-00002.npy',
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--initial-value': None,
 '--length': '32000',
 '--output-html': False,
 '--speaker-id': None,
 '<checkpoint>': './checkpoints/checkpoint_step000210000.pth',
 '<dst_dir>': './mytest'}
Load checkpoint from ./checkpoints/checkpoint_step000210000.pth
Traceback (most recent call last):
  File "synthesis.py", line 181, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 84, in wavegen
    assert c.ndim == 2
AssertionError

**Comment by azraelkuan** [comment]
@dongmh maybe you can use `np.load(xxx.npy)` and print its shape, make it equals to 2.

**Comment by dongmh** [comment]
@imdatsolak  You are right. Thank you.

**Comment by dongmh** [comment]
@azraelkuan Thank you. I should use the mel...npy file.

**Comment by r9y9** [comment]
I added an error handing for the invalid conditional feature case. Does this look better?

```
Traceback (most recent call last):
  File "synthesis.py", line 184, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 86, in wavegen
    "Expected 2-dim shape (T, {}) for the conditional feature, but {} was actually given.".format(hparams.cin_channels, c.shape))
RuntimeError: Expected 2-dim shape (T, 80) for the conditional feature, but (49408,) was actually given.
```

**Comment by r9y9** [comment]
I'm closing this. Feel free to reopen if you still have the issue.
