### ISSUE TITLE
Cannot Load Checkpoint when using pretrained model for cmu_arctic

### ISSUE THREAD

**Issue by zctang** [r9y9/wavenet_vocoder#152]
Hi all:

I cannot load checkpoint as picture shown below:
![Uploading image.png…]()

what's the problem for me?

Thank you.

**Comment by zctang** [comment]
![image](https://user-images.githubusercontent.com/50061822/57344751-06c4fd00-717b-11e9-90b3-0bb3fc25dfc7.png)

**Comment by r9y9** [comment]
Sorry but it's hard to say anything with the provided information.
