### ISSUE TITLE
Speed up waveform generation on inference

### ISSUE THREAD

**Issue by angeloh** [r9y9/wavenet_vocoder#154]
On the Google Colab example https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb, it took a long time to synthesize those short sentences. How to speed up during the inference so it can be used to generate audio from text end to end within a reasonable timeframe?

**Comment by geneing** [comment]
@angeloh Depending on hardware you are going to use, look for papers on WaveGlow or WaveRNN as vocoders. Tacotron is fast enough for generating Mel spectrogram.

**Comment by angeloh** [comment]
@geneing Do you know about long sentences inferences? Do you think Tacotron2 is able to work with more than 1000 characters for generating Mel Spectrogram?

**Comment by geneing** [comment]
@angeloh Autoregressive attention tends to have alignment problems with longer sentences. Recent fastspeech paper has a good discussion and a claimed solution.
