### ISSUE TITLE
IndexError: index 1886 is out of bounds for axis 0 with size 1846

### ISSUE THREAD

**Issue by markyouyuren** [r9y9/wavenet_vocoder#155]
I'm exploring nnmnkwii for singing synthesis.However, I encountered a problem that I could not solve by myself. I would like to ask for your help.My questions are as follows:
         In acoustic feature extraction,the Acoustic linguistic feature dim is (1899, 11349),when the Acoustic feature dim is (1846, 187),This problem caused errors in the training of acoustic models.Error message:
![image](https://user-images.githubusercontent.com/34672671/58857307-788b5a80-86d7-11e9-93da-a879042d7152.png)
![image](https://user-images.githubusercontent.com/34672671/58857331-8b9e2a80-86d7-11e9-99aa-818b30c57a4b.png)

**Comment by r9y9** [comment]
Dup of https://github.com/r9y9/nnmnkwii_gallery/issues/9
