### ISSUE TITLE
Gaussian WaveNet

### ISSUE THREAD

**Issue by r9y9** [r9y9/wavenet_vocoder#157]
Currently, only the MoL is supported for parametric output distribution, but Gaussian output should be pretty easy to implement. I will make some time to support Gaussian perhaps this weekend.

**Comment by rishikksh20** [comment]
Sounds great

**Comment by r9y9** [comment]
Finally, I pushed the code in #164 https://github.com/r9y9/wavenet_vocoder/commit/57a39ee5deb029ec636cadb17cbbff6a6f60f5f0. I will do tests next.
