### ISSUE TITLE
about the sampling rate or data  rate 

### ISSUE THREAD

**Issue by nkcdy** [r9y9/wavenet_vocoder#158]
I have a wave file with 256kbps(16bits16khz).  I converted wave file into Mel spectrogram by change the sampling rate parameter in hparams. py file.  but when I convert the mel spectrogran back to wavefile, I got a wavefile with 512kbps datarate.  the quality of the generated wavefile is quite high.  the model I used is a pre-trained model provided by other project.

**Comment by terryyizhong** [comment]
same question

**Comment by nkcdy** [comment]
the generated wave is 16khz 32bits so the datarate is 512kbps.
