### ISSUE TITLE
Fixing broken dependencies (lws, bandmat) on macOS 10.14

### ISSUE THREAD

**Issue by TheButlah** [r9y9/wavenet_vocoder#159]
Hello,

I wanted to put this here as some friendly help for anyone else running into this issue on macOS 10.14. Initially, I was unable to get this code to work as installing `lws` as well as `bandmat` was not working. 

I was able to solve the issue by compiling `bandmat` manually, as well as `lws`. However, `lws` was initially unable to compile as it appears to be broken on newer installs of Xcode. I have posted a workaround over at the `lws` repo here: https://github.com/Jonathan-LeRoux/lws/issues/7#issuecomment-505667036. Follow those instructions to make a fix for your `setup.py` file, and then proceed to install `lws` from there. 

After that, everything should (hopefully) work!

**Comment by alexiej** [comment]
Hi, I still got an error when I try to install `nnmnkwii` required for this package. ` Running setup.py install for bandmat ... error`, but I installed from the source:
`
git clone git://github.com/MattShannon/bandmat.git
python setup.py build_ext --inplace
`
finished correct, and the library works fine, but still, the pip installation for `nnmnkwii` try to download them from the internet. 
@TheButlah : How you fix this?

**Comment by alexiej** [comment]
I finally found a working workaround. Below instructions for who like I spend hours to figure it out.

1. Clone lws

```
https://github.com/Jonathan-LeRoux/lws.git
```
2. Replace line 41 in the file `python/setup.py` with the above code

```python
ext_modules = [Extension("lws",
                             sources=[lws_module_src,"lwslib/lwslib.cpp"],
                             include_dirs=["lwslib/",np.get_include()],
                             language="c++",
                             extra_compile_args=["-O3", "-stdlib=libc++"],
                             extra_link_args=["-stdlib=libc++"])],
```

3. compile lws

```
cd lws/python
make sdist
pip install dist/lws-1.2.tar.gz
```

4. clone bandmat

```
https://github.com/MattShannon/bandmat.git
```

5. Create distribution and install bandmat

```
cd bandmat
python setup.py sdist
pip install dist/bandmat-0.8.dev1.tar.gz
```

6. Try install `nnmnkwii`

```
pip install nnmnkwii
```
If everything works fine you can install `wavenet_vocoder`

```
pip install -e ".[train]"
```
 or

```
pip install -e ".[test]"
```

**Comment by r9y9** [comment]
I'm working on fixing the dependency problem. 1) I will remove lws dependency from the repo and use librosa instead. 2) I will make bandmat requirement optional for nnmnkwii (https://github.com/r9y9/nnmnkwii/pull/88).

Ref: https://github.com/r9y9/deepvoice3_pytorch/issues/154, https://github.com/MattShannon/bandmat/issues/10

**Comment by r9y9** [comment]
bandmat dependency is fixed now by https://github.com/r9y9/nnmnkwii/pull/88. I will work on lws part afterwards.

**Comment by r9y9** [comment]
By the way, my workaround for new osx versions is https://github.com/SeanNaren/warp-ctc/issues/129#issuecomment-502349652.

**Comment by TheButlah** [comment]
I've spoken with the LWS author and he has updated the code so that the pip package works now. I have tested it on the latest lws version, 1.2.3
