### ISSUE TITLE
"quantize_channels" parameter in JSON file

### ISSUE THREAD

**Issue by byuns9334** [r9y9/wavenet_vocoder#163]
Thanks for the great work!

If I use the 25-bit audio samples for training data, should I set "quantize_channels" parameter as 2^15=33554432? if not, how can I set this parameter?

**Comment by r9y9** [comment]
I guess you might want to learn how parallel wavenet deals with the problem. See sec. 2.1 of https://arxiv.org/abs/1711.10433 for details.

In short: we can consider using an explicit parametrized distribution to model raw audio.
