### ISSUE TITLE
Generalization ability?

### ISSUE THREAD

**Issue by miaoYuanyuan** [r9y9/wavenet_vocoder#166]
@r9y9 Thank you for your great work! but i have meet some questions,I need your help:
1.can we use the pretrained model trained on LJSpeech to inference  other data such as cmu ,vctk?
2.when training on multi people ,can we mixtured all data in one dataset without distinguish speaker id?

**Comment by r9y9** [comment]
Hi, here are my answers:

1. No. You need to finetune the model to the other data or you can consider universal vocoder-like approach. https://arxiv.org/abs/1811.06292.
2. Yes, I think it's possible. I like the approach (actually this is what universal vocoding does)

**Comment by miaoYuanyuan** [comment]
> Hi, here are my answers:
> 
>     1. No. You need to finetune the model to the other data or you can consider universal vocoder-like approach. https://arxiv.org/abs/1811.06292.
> 
>     2. Yes, I think it's possible. I like the approach (actually this is what universal vocoding does)

Thank you for your reply!  there is another question: waveglow is also trained on LJSpeech dataset,why it can generated to other dataset?
