### ISSUE TITLE
Which version for training unconditional WaveNet?

### ISSUE THREAD

**Issue by roberthoenig** [r9y9/wavenet_vocoder#167]
The README states the following:

>Training un-conditional WaveNet
NOTICE: This is probably not working now. Please check v0.1.2 for the working version.

Looking at the [releases](https://github.com/r9y9/wavenet_vocoder/releases), it seems that v0.1.1 is the most recent version. Does training unconditional WaveNets work with v0.1.1, or is the point of the README that it'll be supported in some future version?

**Comment by r9y9** [comment]
Oops, my bad. I meant v0.1.1. Yes, it should work with v0.1.1. It won’t be difficult to support unconditional WaveNet on master, but it’s not on my list at the moment.

**Comment by roberthoenig** [comment]
Thanks for the heads up!
