### ISSUE TITLE
pitch shifted output

### ISSUE THREAD

**Issue by lingjzhu** [r9y9/wavenet_vocoder#170]
Hi I have trained a wavenet on a Mandarin dataset and the evaluation result is really amazing! Thanks for the great work.

May I ask a question about using the wavenet?
I also trianed a Tacotron2 using the Nvidia/Tacotron2 repo. When I tried to use the pre-trained wavenet for synthesis I was only able to get a pitch shifted output, though I have converted the Tacotron2 output to log mel spectrogram and normalized using the wavenet meanvar parameters. The Griffin-Lim synthesized sample sounds not so good but the pitch is correct. 
[wavenet_sample.zip](https://github.com/r9y9/wavenet_vocoder/files/3673791/wavenet_sample.zip)
[griffin-lim_sample.zip](https://github.com/r9y9/wavenet_vocoder/files/3673793/griffin-lim_sample.zip)
I thought this might be due to the difference in preprocessing steps. From my reading of the code, the processing in your repo is only to compute the log mel spectrogram and do meanvar normalization. Is my understanding correct? Thanks!

I foudn the code snippet from NVIDIA/tacotron2#40 but it seems that hparams.min_level_db is no longer present.
```
 # methods from from NVIDIAs repo
mel = torch.load(conditional_path)
mel = dynamic_range_decompression(mel)
mel = mel.cpu().numpy()
mel = mel.transpose()
# methods from from Ryuchi's repo
mel = audio._amp_to_db(mel) - hparams.ref_level_db
if not hparams.allow_clipping_in_normalization:
    assert mel.max() <= 0 and mel.min() - hparams.min_level_db >= 0
mel = audio._normalize(mel)`
```

**Comment by lingjzhu** [comment]
OK. I solved it now. I used the same processing step to generate the log mel spectrogram and retrained the Tacotron2 model. The synthsized results are pretty amazing only using the Tacotron2 outputs. Thanks for the great work!

**Comment by r9y9** [comment]
I'm glad that you solved it by yourself.
