### ISSUE TITLE
normalization method

### ISSUE THREAD

**Issue by james20141606** [r9y9/wavenet_vocoder#172]
I found in compute-meanvar-stats.py it uses standard scaler to do normalization. For spectrogram, I am not sure if it is right to do normalization on 2D matrix. I have observed that if we apply normalization on 2D matrix, it is  a little weird. However, if applied to 1D vector (ravel 2D matrix to 1D) it makes more sense. Do you consider this situation?

**Comment by r9y9** [comment]
Normalization for each feature dimension is pretty common in my opinion. I don't think it's weird.
