### ISSUE TITLE
Local and global conditioning feature 

### ISSUE THREAD

**Issue by shiva1393** [r9y9/wavenet_vocoder#178]
Hai
    Now this github code supporting global and local conditioning features?. I didn't understood for global conditioning use v0.1.1. From current  code can i  train cmu artic data set by giving global 
 and local conditioning  feats.
and in preprocess step 
db_root=~/data/LJSpeech-1.1/wavs/
here wavs have single speaker but cmuartic have 7 speakers if we combine all wave files into one folder then at which step script devide data into 7 different speakers.
Please can any one answer this questions.

**Comment by r9y9** [comment]
Please check https://github.com/r9y9/wavenet_vocoder/releases/tag/v0.1.1.

**Comment by shiva1393** [comment]
Trained multi-speaker wavenet for cmu-arctic dataset but didn't get reconstructed wave file like which mentioned in "https://r9y9.github.io/wavenet_vocoder/".  For LJSpeech got good results.

By following readme file:
step1)
python preprocess.py cmu_arctic $db_root $data_feats --preset=multispeaker_cmu_arctic_mixture.json
step2)
python train.py --data-root=$data_feats
please tell what i have to change(or where iam doing mistake) while training multi-speaker wavenet.
