### ISSUE TITLE
Fast wavenet

### ISSUE THREAD

**Issue by narcise** [r9y9/wavenet_vocoder#180]
would you help me to find which part of the code is about Fast inference by caching intermediate states in convolutions?

**Comment by r9y9** [comment]
Please see https://github.com/r9y9/wavenet_vocoder/blob/a835a8eebfec5e049d93f629c4ee2f1daab56329/wavenet_vocoder/conv.py#L17-L46.

`self.input_buffer` is the intermediate state.
