### ISSUE TITLE
Running wavenet with low inference

### ISSUE THREAD

**Issue by qo4on** [r9y9/wavenet_vocoder#186]
Can you share a link to an example of running wavenet faster than this [Online TTS demo](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb)?

**Comment by r9y9** [comment]
This is a won't fix request. You might want to take a look at https://github.com/kan-bayashi/ParallelWaveGAN for faster waveform generation.
