### ISSUE TITLE
tensorflow error in notebook file

### ISSUE THREAD

**Issue by nathphoenix** [r9y9/wavenet_vocoder#189]
this was working before, but i just wana run it now, i'm getting getgraph function not available, and i have tried other versions of tensorflow, but resulting to different errors

**Comment by MohammadJavadD** [comment]
Have you tried tensorflow==1.6 ?

**Comment by nathphoenix** [comment]
> **Have you tried tensorflow==1.6 ?**

yes i have, but finally change the keras version to make it work
will be working to create my own model soon using this repo
