### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by nathphoenix** [r9y9/wavenet_vocoder#192]
**please help me, i have run the code again, this is the error for each the two file, i run the wavallin.py file to see if the audio dataset was properly loaded in order to know why the preprocess.py file is giving error**  @r9y9 @aleksas @candlewill 

![Screenshot (1468)](https://user-images.githubusercontent.com/28567522/81642713-ed086680-941b-11ea-96e7-1fd0b50c0419.png)

$ python preprocess.py wavallin ~/LJSpeech-1.1 ./ljspeech --preset=params
Sampling frequency: 22050
C:\Users\Maxwell\Documents\TacoProject\Tacotronvenv\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.  
  warnings.warn(message, FutureWarning)
0it [00:00, ?it/s]
Wrote 0 utterances, 0 time steps (0.00 hours)
Traceback (most recent call last):
  File "preprocess.py", line 71, in <module>
    preprocess(mod, in_dir, out_dir, num_workers)
  File "preprocess.py", line 25, in preprocess
    write_metadata(metadata, out_dir)
  File "preprocess.py", line 36, in write_metadata
    print('Min frame length: %d' % min(m[2] for m in metadata))
ValueError: min() arg is an empty sequence

$ cd datasets
(Tacotronvenv)
Maxwell@Nathaniel MINGW64 ~/Documents/TacoProject/wavenet_vocoder/datasets (master)
$ python wavallin.py
Traceback (most recent call last):
  File "wavallin.py", line 5, in <module>
    import audio
ModuleNotFoundError: No module named 'audio'
(Tacotronvenv)

here the audio.py file is been seen an installed module

**Comment by r9y9** [comment]
It looks like you specified the wrong path: `~/LJSpeech-1.1` should be `~/LJSpeech-1.1/wavs`.

By the way, I would like to warn you regarding the following two points:

- Please do not tag random people. It would annoy people who are not interested in the issue.
- Please spend your time first to investigate your issues, otherwise, no one wants to help you out.

I generally want to help people out as possible as I can, but your case sounds too elementary to me. I'd recommend you to first learn python basics.

**Comment by nathphoenix** [comment]
sorry about that, i use the path you had prescribed in your documentation, initially i use to get file path error, and i didn't get that after using this path and one other one, i have been writing for over a year now, even though is not 10 years of experience, i have built several apps, flask and the rest with deep learning.... this is the current project i'm working on just need your help
thank you if you see this @r9y9

**Comment by nathphoenix** [comment]
will look closely again.... thank you

**Comment by nathphoenix** [comment]
is working now, i didn't specify the wavs folder 
python preprocess.py wavallin C:/Users/Maxwell/Documents/TacoProject/wavenet_vocoder/LJSpeech-1./wavs C:/Users\Maxwell/Documents/TacoProject/wavenet_vocoder
