### ISSUE TITLE
Training directory error

### ISSUE THREAD

**Issue by lordcode-max** [r9y9/wavenet_vocoder#196]
Nice work @r9y9, your work is helping me in my master degree project, thanks so much.
However, i was stuck on training after i have preprocess my data to this directory ./sounded/audio.
Using this command for training: python train.py --dump-root=./sounded/audio --preset=params.
i even followed a similar pattern with someone like this:
python train.py --data-root=./data/BZNSYP/ --speaker-id=0 --hparams="cin_channels=80,gin_channels=-1"
  and also tried to use different version of nnmnkwii modules which is not still working
keeps on getting this error from the nnmnkwii modules that: "No files are collected. You might have specified wrong data source." which i pointed to the audio folder containing the output from the preprocess run 
Thank you in advance

**Comment by r9y9** [comment]
https://github.com/r9y9/wavenet_vocoder/blob/63d3fe0a85a69aa25d80700974fe282c96fb6b65/train.py#L982-L995

Please make sure your have at leaset two directories in dump root: `train_no_dev` and `dev`. Also please first check working **recipes**, rather than directly invoking CLI scripts.

**Comment by lordcode-max** [comment]
i'm grateful for your response, i have included train_no_dev and dev folders in my dump root directory containing all my preprocessed output, but still giving me same error, please correct me if i'm mistaken,
i have gone through the nnmnnkwii file to check the function that was called in collecting the files from the dump root directory and i notice that the collectfiles() didn't do anything other than raising errors
![Screenshot (1497)](https://user-images.githubusercontent.com/65525660/82195882-d7e67880-98f0-11ea-9100-96fd3895c3c8.png)
![Screenshot (1498)](https://user-images.githubusercontent.com/65525660/82195889-dae16900-98f0-11ea-958b-849789395d2a.png)

**Comment by r9y9** [comment]
I am sorry if I am wrong but you must be the same person as https://github.com/r9y9/wavenet_vocoder/issues/194. I can see exactly the same directory, asking for the same question. I will close this issue as this is a problem on your side. The error should not happen if you run one of the provided recipes.
