### ISSUE TITLE
+0.01 in audio._amp_to_db(x) ???

### ISSUE THREAD

**Issue by duvtedudug** [r9y9/wavenet_vocoder#22]
What is the reason for raising the floor of the spectrogram in the amp to db function?

Did this give better sound quality?

```
def _amp_to_db(x):
    return 20 * np.log10(np.maximum(1e-5, x + 0.01))  # why the + 0.01??


def _db_to_amp(x):
    return np.power(10.0, x * 0.05) # - 0.01 should be at end there??
```

And a small point, should the inverse function not have - 0.01 at the end to compensate for this?

Thanks in advance!

**Comment by r9y9** [comment]
This is a method mentioned in the secton 2.2 of the Tacotron2 paper (https://arxiv.org/pdf/1712.05884.pdf) to limit dynamic range of mel-spectrum values.

> And a small point, should the inverse function not have - 0.01 at the end to compensate for this?

I think you are right. I forgot to do that, though it's never used in the repository. Will fix this in https://github.com/r9y9/deepvoice3_pytorch, Thanks!

**Comment by PetrochukM** [comment]
Concerning the clip at 0.01, does clip not imply a ``np.maximum(x, 0.01)``. Why is 0.01 used as an offset rather than clip?
