### ISSUE TITLE
Why the discretized_mix_logistic_loss get nan？

### ISSUE THREAD

**Issue by jiqizaisikao** [r9y9/wavenet_vocoder#23]
Hi:
    I used your vocoder in my project and set the log_scale_min=float(np.log(1e-4)) and some other value bigger,why it still got nan loss ,will overflow happens at this situation?

**Comment by r9y9** [comment]
Please provide exhaustive information as much as possible. Otherwise we cannot help you much.

**Comment by jiqizaisikao** [comment]
thanks,maybe because i put the clip_grad_norm before loss backward ,i will try put it after the loss backward
