### ISSUE TITLE
Thanks,i will try the mixture model again

### ISSUE THREAD

**Issue by jiqizaisikao** [r9y9/wavenet_vocoder#25]
ok,i will try the mixture model again

**Comment by jiqizaisikao** [comment]
1 ,I  get output y_hat from category model from your code
2 ,I calculate z=abs(stft(y_hat)-stft(x))
3, it seems that z can not backward

**Comment by r9y9** [comment]
So It seems your stft doesn’t implement backward.

**Comment by jiqizaisikao** [comment]
No,the stft is from some other project and it can backward loss,i have tested it ,it seems that the category output  can not backwad loss
