### ISSUE TITLE
Error in extracting melspectrogram

### ISSUE THREAD

**Issue by Feng-long** [r9y9/wavenet_vocoder#26]
Hi, @r9y9 
     I am using your tool to preprocess the waveform of LJspeech database. However I meet this assertion error in melspectrogram extraction  for every utterance.  assert S.max <=0 and S.min-hparams.min_level_db >=0  I see you set min_level_db=-100, ref_level_db=20. Shall I set different values depends on the speech database? or Did I misunderstood something?

Thanks

**Comment by r9y9** [comment]
That's a sign that clipping happened during feature normalization. Using default parameters I believe clipping rarely happens and doesn't affect speech quality much, though. I changed hyper param so you will not see the assertion anymore.
