### ISSUE TITLE
About the synthesis time

### ISSUE THREAD

**Issue by LCLL** [r9y9/wavenet_vocoder#28]
Hi, r9y9,
       Thanks for sharing the great work. Can you share the detail time for synthesis a wav? Thank you.

**Comment by r9y9** [comment]
I don't have an answer right now, but that would be best if you can try it yourself? :)

**Comment by jiqizaisikao** [comment]
My GPU is GTX1070ti and the synthesis a wav of 1S will take about 3 minuts

**Comment by nsmetanin** [comment]
On Tesla M60 it takes ~7.5mins to generate 1 second of audio (with default params)

**Comment by zhf459** [comment]
Hope to see the powerful Parallel Wavenet

**Comment by gauss256** [comment]
On a GTX 1080 Ti it took about 2.7 minutes per second of output audio.

**Comment by tomse-h** [comment]
Is Multi-GPU synthesis a thing? Only one of my GPU is used at a time, would love to see an increase in generation speed using multiple GPUs.

**Comment by Ala2dz** [comment]
on GTX 1080Ti it does 27.33it/s
