### ISSUE TITLE
Wave Noise

### ISSUE THREAD

**Issue by weixsong** [r9y9/wavenet_vocoder#3]
Hi,

In your demo waves, I notice some glitch noise, this noise may be generated by the WaveNet random sampling feature.

Do u have further updated model that without such kind of noise?

**Comment by r9y9** [comment]
I do plan to update and improve my implementation. I'm guessing the glitch noise is due to limited training data (only 1 hour) and insufficient training time (~22 hours).

**Comment by r9y9** [comment]
I'm closing this. Feel free to reopen if you have any further comments on this.
