### ISSUE TITLE
Why lws and not regular stft?

### ISSUE THREAD

**Issue by duvtedudug** [r9y9/wavenet_vocoder#35]
Is there a reason for using lws?

Do you use reconstructed phase somewhere to improve quality?

Thanks in advance, Duvte.

**Comment by r9y9** [comment]
> Do you use reconstructed phase somewhere to improve quality?

No. 

The reason is that I wanted to integrate the vocoder with https://github.com/r9y9/deepvoice3_pytorch, which uses lws. I needed to use same audio feature extraction pipeline. See https://github.com/r9y9/deepvoice3_pytorch/pull/21 for wavenet vocoder integration with DeepVoice3.

**Comment by duvtedudug** [comment]
That makes sense, thanks!

How close are you to integrating DeepVoice3 together with WaveNet Vocoder?

**Comment by r9y9** [comment]
It will take me a few months :(
