### ISSUE TITLE
Using DeepVoice3 mels spectrogram as wavenet vocoder's input 

### ISSUE THREAD

**Issue by yishaicohe** [r9y9/wavenet_vocoder#39]
I hope anyone can help me with a problem I got while trying to run both DeepVoice3 and Wavenet systems.

When I run TTS with Deepvoice3 on LJSpeech, I got a robotic sound.
I know that Wavenet can predict a better reasults.
I extract the mel spectrogram from DeepVoice3 system (hopefully I did it right) and tried to set it as an input for the Wavenet system.
The results weren't so good, as the voice still has a robotic sound and lots of background whistling.

I am using UBUNTU 16.04 os.
The model I used is LJ 410K iters

Hopefully anyone has any advice how can I improve results.

Thank in advance,
Yishai

**Comment by SvenShade** [comment]
Yeah, I'm currently training on solo instrumental audio, and experiencing this same background whistling! Anyone else experienced the same thing, or know what might be causing it?

**Comment by Shridharpawar77** [comment]
I am also facing same problem. Did anyone solved the problem?
