### ISSUE TITLE
when synthesis a wav file use synthesis.py, crash！

### ISSUE THREAD

**Issue by neverjoe** [r9y9/wavenet_vocoder#4]
Traceback (most recent call last):
  File "synthesis.py", line 151, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 103, in wavegen
    initial_input, c=c, g=g, T=length, tqdm=tqdm, softmax=True, quantize=True)
  File "wavenet.py", line 234, in incremental_forward
    assert c.size(-1) == T
AssertionError

**Comment by r9y9** [comment]
This is not crash :( Can you elaborate on what you are trying?

**Comment by neverjoe** [comment]
i maybe  use it in wrong way, 
python3 synthesis.py    --length=16000  --initial-value=128  --conditional=data/mel-06910.npy  checkpoints/checkpoint_step000010000.pth  checkpoints/audio/
some hparams is:
    upsample_conditional_features=True,
    # should np.prod(upsample_scales) == hop_size
    upsample_scales=[16, 16],
    # Freq axis kernel size for upsampling network
    freq_axis_kernel_size=3,

**Comment by r9y9** [comment]
Sorry for the inconvenience. This is still much WIP, but I will try to add a brief README soon. I'm afraid I'm not using `upsample_conditional_features` for now and don't have a quick fix for you. I will look into it today.

**Comment by neverjoe** [comment]
thx for your great work,  you have done a lot.

**Comment by r9y9** [comment]
@neverjoe I think I fixed the issue. Could you check if it works?

**Comment by r9y9** [comment]
Added getting started guide to the README

**Comment by neverjoe** [comment]
it works!

**Comment by r9y9** [comment]
:+1:
