### ISSUE TITLE
Speech to Speech

### ISSUE THREAD

**Issue by PetrochukM** [r9y9/wavenet_vocoder#42]
Does it make sense to use the Wavenet vocoder as it is for speech to speech? For example, Can I record my voice, generate a melspectrogram, then use a pre-trained model on LJSpeech dataset to respeak it?

I've been trying this and the results don't sound good.

**Comment by pfriesch** [comment]
The problem is that the speaker (you) was not in the training set. You could try to record a bit of audio of yourself, remove all the silences and fine-tune on that.

**Comment by PetrochukM** [comment]
Have their been experiments to train multi-speaker to speaker? Train the model to generally be able to take any voice and convert it into a single voice? Do you know?

**Comment by PetrochukM** [comment]
It's interesting from a voice actor perspective. What if there was no need for studio equipment or multiple voice actors? Developers could record clips and professional sounding audio in a particular voice would be generated.

**Comment by duvtedudug** [comment]
This would probably be possible but you would need a vocoder that is not based on mel spectrograms, but based on traditional parameters like f0, phoneme, timings etc. @r9y9 's is based on mel spectrograms.
