### ISSUE TITLE
Is Implementation with Google's Cloud TPUs possible?

### ISSUE THREAD

**Issue by mrsylerpowers** [r9y9/wavenet_vocoder#43]
Is it possible for this project to be implemented with [Google's Cloud TPUs](https://cloud.google.com/tpu/) . My Assumption it it would make it a lot easier for training if one could get a quota for a TPU and would run off the same platform that the [Google Assistant](https://www.xda-developers.com/deepmind-wavenet-google-assistant-tpu/) runs off of.

**Comment by r9y9** [comment]
Can I get access to TPUs? :-)

**Comment by mrsylerpowers** [comment]
@r9y9 I have asked google and got approval for 2x2 TPU for this project named [tpu-tts](https://console.cloud.google.com/home/dashboard?project=tpu-tts) if anyone wants to have access just ask and send me your gmail.
