### ISSUE TITLE
Google releases Cloud TTS speak engine that uses wavenet 

### ISSUE THREAD

**Issue by mrsylerpowers** [r9y9/wavenet_vocoder#44]
Google just released a [Cloud TTS](https://cloud.google.com/text-to-speech/) service that uses wavenet.
> Google Cloud Text-to-Speech enables developers to synthesize natural-sounding speech with 30 voices, available in multiple languages and variants. It applies DeepMind’s groundbreaking research in WaveNet and Google’s powerful neural networks to deliver the highest fidelity possible. As an easy-to-use API, you can create lifelike interactions with your users, across many applications and devices.

**Comment by geneing** [comment]
Maybe on could one use cloud tts to generate clean training data (e.g. an alternative to LJSpeech dataset). Models trained on this data won't sound better wavenet, though.
