### ISSUE TITLE
the problem of pre-model

### ISSUE THREAD

**Issue by YanHengxu** [r9y9/wavenet_vocoder#49]
When I use the pre-model ,an error appears,I don't know the reason.Can you give me some suggestions? Thank you very much 
yan@yan-Default-string:~/文档/beifen/wavenet_vocoder-master$ python synthesis.py --conditional=./data/ljspeech/ljspeech-mel-00001.npy ./checkpoints/checkpoint_step000410000_ema.pth generated
/home/yan/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Command line args:
 {'--conditional': './data/ljspeech/ljspeech-mel-00001.npy',
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--initial-value': None,
 '--length': '32000',
 '--output-html': False,
 '--preset': None,
 '--speaker-id': None,
 '<checkpoint>': './checkpoints/checkpoint_step000410000_ema.pth',
 '<dst_dir>': 'generated'}
Load checkpoint from ./checkpoints/checkpoint_step000410000_ema.pth
Traceback (most recent call last):
  File "synthesis.py", line 175, in <module>
    checkpoint = torch.load(checkpoint_path)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 405, in _load
    return legacy_load(f)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 341, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/home/yan/anaconda3/lib/python3.6/tarfile.py", line 2038, in extract
    tarinfo = self.getmember(member)
  File "/home/yan/anaconda3/lib/python3.6/tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"

**Comment by r9y9** [comment]
I'm not sure why the error happens, but it seems there's a related issue on pytorch/examples: https://github.com/pytorch/examples/issues/205.

**Comment by YanHengxu** [comment]
Thank you very much!

Today, I generated audio using a model that trained 500,000 steps. The effect was the same as the one you generated. However, when I imported the MEL spectograms generated by Rayhane-mamah/Tacotron-2 into your model, The following error, can you explain it？
python synthesis.py --conditional=./checkpoints/ljspeech-mel-prediction-step-85600.npy ./checkpoints/checkpoint_step000500000_ema.pth generated
/home/yan/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Command line args:
 {'--conditional': './checkpoints/ljspeech-mel-prediction-step-85600.npy',
 '--file-name-suffix': '',
 '--help': False,
 '--hparams': '',
 '--initial-value': None,
 '--length': '32000',
 '--output-html': False,
 '--preset': None,
 '--speaker-id': None,
 '<checkpoint>': './checkpoints/checkpoint_step000500000_ema.pth',
 '<dst_dir>': 'generated'}
Load checkpoint from ./checkpoints/checkpoint_step000500000_ema.pth
  0%|                                                 | 0/20480 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "synthesis.py", line 185, in <module>
    waveform = wavegen(model, length, c=c, g=speaker_id, initial_value=initial_value, fast=True)
  File "synthesis.py", line 124, in wavegen
    log_scale_min=hparams.log_scale_min)
  File "/home/yan/文档/beifen/wavenet_vocoder-master/wavenet_vocoder/wavenet.py", line 335, in incremental_forward
    x, h = f.incremental_forward(x, ct, gt)
  File "/home/yan/文档/beifen/wavenet_vocoder-master/wavenet_vocoder/modules.py", line 125, in incremental_forward
    return self._forward(x, c, g, True)
  File "/home/yan/文档/beifen/wavenet_vocoder-master/wavenet_vocoder/modules.py", line 155, in _forward
    c = _conv1x1_forward(self.conv1x1c, c, is_incremental)
  File "/home/yan/文档/beifen/wavenet_vocoder-master/wavenet_vocoder/modules.py", line 43, in _conv1x1_forward
    x = conv.incremental_forward(x)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/deepvoice3_pytorch/conv.py", line 46, in incremental_forward
    output = F.linear(input.view(bsz, -1), weight, self.bias)
  File "/home/yan/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch at /pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:247


This audio is the result of my training of 500,000 steps. 

[checkpoint_step000500000_ema.wav.zip](https://github.com/r9y9/wavenet_vocoder/files/1914664/checkpoint_step000500000_ema.wav.zip)
The audio is a mel spectrogram generated with Rayhane-mamah/Tacotron-2. 
[Uploading checkpoint_step000500000_ema-1.wav.zip…]()

The speech synthesized with the griffin_lim algorithm is preprocessed into an .npy file and input into your model, but the effect is not very good. Can you explain it? Many thanks

**Comment by ChenXi1992** [comment]
The mel spectrogram in this project is derived from the audio directly. However, the mel spectrogram that you're using from  Rayhane-mamah/Tacotron-2 is the prediction based on the S2S model. It's predictable that the "quality" of the mel spectrogram from Rayhane-mamah would be poor.

**Comment by siminchai** [comment]
@YanHengxu  Hi there, may I ask how did you solve the '"filename 'storages' not found"' issue? I met the same problem.

Thanks!!
