### ISSUE TITLE
Support for pytorch v0.4

### ISSUE THREAD

**Issue by r9y9** [r9y9/wavenet_vocoder#54]

**Comment by danshirron** [comment]
Need to change in train.py line 496 to:
    length = input_lengths[idx].data.cpu().item()

Old code was:
length = input_lengths[idx].data.cpu().numpy()[0]
This causes "IndexError: too many indices for array"

Thanx @azraelkuan for the tip

**Comment by r9y9** [comment]
Thanks for pointing this out. Will be fixed by #58.
