### ISSUE TITLE
preprocess error

### ISSUE THREAD

**Issue by azraelkuan** [r9y9/wavenet_vocoder#6]
when i run the preprocess.py, the lws will raise a error: 
`TypeError: '>' not supported between instances of 'NoneType' and 'int'`,
should I use `return lws.lws(hparams.fft_size, get_hop_size(), mode="speech", fftsize=hparams.fft_size)`
[the error line](https://github.com/r9y9/wavenet_vocoder/blob/39961f5d62ae0d0d338d64719ddf6af0760f3053/audio.py#L81)

**Comment by r9y9** [comment]
What version of lws are you using? Might be same as https://github.com/r9y9/deepvoice3_pytorch/issues/8

```
In [3]: import pkg_resources

In [4]: pkg_resources.get_distribution("lws")
Out[4]: lws 1.0 (/home/ryuichi/anaconda3/lib/python3.6/site-packages)
```

**Comment by azraelkuan** [comment]
Oh, yes. My lws is version 1.1. Thanks!

**Comment by r9y9** [comment]
I'd recommend you to run `pip install -e ".[train]"` which installs proper versions of dependencies.

https://github.com/r9y9/wavenet_vocoder/blob/39961f5d62ae0d0d338d64719ddf6af0760f3053/setup.py#L54-L74
