### ISSUE TITLE
Fast Wavenet Generation Algorithm

### ISSUE THREAD

**Issue by r9y9** [r9y9/wavenet_vocoder#61]
Paper: https://arxiv.org/abs/1611.09482

Code:

- https://github.com/vincentherrmann/pytorch-wavenet
- https://github.com/dhpollack/fast-wavenet.pytorch

**Comment by phiresky** [comment]
Yes please 👍

**Comment by nsmetanin** [comment]
Is there any room for improvement towards the Fast WaveNet? It seems that input_buffer already works just like "dilation queues" described in the Fast WaveNet paper — https://github.com/r9y9/wavenet_vocoder/blob/master/wavenet_vocoder/conv.py#L39

I've profiled the inference for 2048 samples and got the following output of cProfile:

![image](https://user-images.githubusercontent.com/764902/40078896-b1ef854e-588e-11e8-94c0-f6fdb4280108.png)

As you can see, the number of convolution calls per sample equals to 202752 / 2048 = 99, which is pretty reasonable for 24-layer model with global and local conditioning.

Is it possible to improve these numbers drastically without changing the model architecture?

**Comment by r9y9** [comment]
Ah, you are right. What we do currently is pretty much of the same idea; caching the intermediate states. This was actually done quite a while ago. https://github.com/r9y9/deepvoice3_pytorch/commit/11a890375ce1f9e995fd31653f327e960b70e4c7

For the record, here's generation timing info:

| Env                                  | Time per samples (sec) |
|--------------------------------------|--------------------------------|
| Google Colab                         | 0.03 [29it/s]                  |
| My desktop PC (GTX 1080Ti, i7-7700K) | 0.008 [130it/s]                |

Params:
https://github.com/r9y9/wavenet_vocoder/blob/4116d34eddd3f841a905660d761d186b483f1846/hparams.py#L52-L62

<img width="581" alt="2018-05-16 11 58 36" src="https://user-images.githubusercontent.com/1220272/40094190-84228a68-5900-11e8-83ee-aa1a0f80d93d.png">

Compared to the results from the paper, although the conditions are different, It seems reasonable to me. 

Can we close the issue? If there's something we can do better, please let me know.

**Comment by nsmetanin** [comment]
I hope that https://github.com/NVIDIA/nv-wavenet/ will be able to perform the inference in near real-time, when they publish python (PyTorch) bindings.

**Comment by r9y9** [comment]
Yes, I'm looking forward to it. I'm closing the issue for now.
