### ISSUE TITLE
[train.py] Padding value inside batched samples is wrong, especially mulaw_quantize setting.

### ISSUE THREAD

**Issue by a3626a** [r9y9/wavenet_vocoder#77]
https://github.com/r9y9/wavenet_vocoder/blob/2b557d4cbacef52bc3441fc4f2c54b1351ae9df4/train.py#L420-L433

The code above pads to batched samples to fit their sequence length. When `is_mulaw_quantize(hparams.input_type) == True`, padding value seems wrong. In this code, `0` is always padded. I think valid padding is `P.mulaw_quantize(0, hparams.quantize_channels)`, not `0`. (P.mulaw_quantize(0, 256) is 128 or something similar)

In `ljspeech.py`, padding is already done like `P.mulaw_quantize(0, hparams.quantize_channels)`.
https://github.com/r9y9/wavenet_vocoder/blob/2b557d4cbacef52bc3441fc4f2c54b1351ae9df4/ljspeech.py#L40-L49

**Comment by r9y9** [comment]
Sorry for the delay. I think you are right. Would you mind creating a PR?

**Comment by a3626a** [comment]
Delay is okay.

I found this bug at https://github.com/Rayhane-mamah/Tacotron-2/issues/55, and I'm not even installed PyTorch in my environment. It is hard to create a PR for me.

**Comment by r9y9** [comment]
Ok, then I will fix it when I have some time. Thanks!
