### ISSUE TITLE
arctic multi speaker generate

### ISSUE THREAD

**Issue by azraelkuan** [r9y9/wavenet_vocoder#8]
hi, i am doing with wavenet vocoder using tensorflow, and i generate good voice using arctic, ljspeech and chinese dataset if not with speaker id. i want to ask:

if i want to generate the wav of the speaker id 0 in arctic dataset, should i use the local condition of speaker id 0, or i can use local condition of any other speaker id ?

- speaker id 0 + local condition 0 ==> wav of speaker id 0 (good)
- speaker id 1 + local condition 0 ==> also the wav of speaker id 0 

i notice that in the repository ibab/tensorflow-wavenet, he can generate the wav of any speaker id

**Comment by azraelkuan** [comment]
i notice the comment in your gitpage, thanks.

**Comment by miaoYuanyuan** [comment]
hi, i  am doing the same thing as you ,could i know which chinese dataset that you choosed to train ?

**Comment by azraelkuan** [comment]
@miaoYuanyuan i use my own dataset, but now u can use the public chinese dataset
https://mp.weixin.qq.com/s/FnYMw7_FcJcd66kw5Hc0Ag

**Comment by miaoYuanyuan** [comment]
@azraelkuan wow,that's great ,thank you~
