### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by brebetez** [r9y9/wavenet_vocoder#80]
I'm just starting to use the project and I was on English until now. But my goal is to make a voice in German and/or french. Both languages contain some specifics characters (for example: à é è ä ö ü ç and more). Should I define a specific char chain? Or it will automatically working? I'm just asking, before to jump in a big session of training...for nothing. ;)

Thank you for your support.

**Comment by r9y9** [comment]
The WaveNet vocoder itself is language independent. In this repository, a model assumes that input is mel-spectrograms (can be any though) and output is raw waveforms. You can use the WaveNet vocoder for any language.

**Comment by aleksas** [comment]
@brebetez Please see [THE LINKS](https://github.com/r9y9/wavenet_vocoder#online-tts-demo) on main page referencing example of using pretrained [Tacotron](https://github.com/Rayhane-mamah/Tacotron-2) and [Wavenet Vocoder](https://github.com/r9y9/wavenet_vocoder) models for text-to-speech evaluation. So essentially in this case there are two parts for TTS: [Tacotron](https://github.com/Rayhane-mamah/Tacotron-2), that generates spectrograms from text and the second is [Wavenet Vocoder](https://github.com/r9y9/wavenet_vocoder) that generates waveforms (audio) from spectrograms. This Git repository is holding the second - [Wavenet Vocoder](https://github.com/r9y9/wavenet_vocoder) part.

If you will decide to try train also the [Tacotron](https://github.com/Rayhane-mamah/Tacotron-2) take a look at least at [these](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/hparams.py#L7-L9), [these](https://github.com/Rayhane-mamah/Tacotron-2/blob/1547b2502305f4ee58bceede1384054c22b0497a/tacotron/utils/cleaners.py#L9-L10) and [these](https://github.com/Rayhane-mamah/Tacotron-2/blob/master/tacotron/utils/symbols.py#L11) lines hinting to what should be done to deal with special characters.

**Comment by aleksas** [comment]
@r9y9 correct me if I'm wrong to properly train [Tacotron](https://github.com/Rayhane-mamah/Tacotron-2) `preprocess.py` and `train.py` have to be executed with same hparams that are used in [codelab synthesis example](https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb)  to synthesize Tacotron spectrograms for wavenet vocoder, i.e. `--hparams='symmetric_mels=False,max_abs_value=4.0,power=1.1,outputs_per_step=1'`, correct?

**Comment by r9y9** [comment]
@aleksas At training-time you need one more: `use_lws=True`. You would need to same audio related hparams. The commit https://github.com/r9y9/Tacotron-2/commit/be036e3d198c4ae2da4380986f5e303150d61a20 might help you what you need to adjust.

**Comment by brebetez** [comment]
@aleksas and @r9y9 thank you for the information. I will read it and have a look more in details. If I have futher question, I'll come back to you.
