### ISSUE TITLE
are these the same channel numbers in original paper?

### ISSUE THREAD

**Issue by hrbigelow** [r9y9/wavenet_vocoder#82]
Hi,

Thanks so much for such a thorough implementation of WaveNet.  I just wondered, do your default hparams channel sizes reflect those used in the final version of the original paper?  I'm new to the field of AI (coming from Biology research) and am puzzled why the authors wouldn't provide a short paragraph listing all of their final hyperparameters, so others could attempt to reproduce their results.  But, maybe I'm missing something.  Is their implementation available somewhere?

Thanks very much!

**Comment by azraelkuan** [comment]
u can check ibab's wavenet, that is origin.

**Comment by r9y9** [comment]
As far as I remember correctly, they don't provide complete implementation details, Taco2 and Parallel WaveNet papers provide some details more than the original paper though. I'm not trying to replicate their papers *exactly*, trying same ideas instead.

**Comment by hrbigelow** [comment]
Hi Ryuichi,

Thanks for checking into it.  I did read ibab/tensorflow-wavenet, and he
mentions in the readme that they don't specify channel numbers in the
original paper.  Tacotron2 does mention they use 3 x 10 layer blocks, but
don't seem to mention channel numbers either.

In your experience, when you find a paper that doesn't give enough details,
do you have some technique for figuring out how to replicate their
results?  It seems it would be hard to do research otherwise...

Thanks again,

Henry


On Sun, Jun 17, 2018 at 12:03 AM, Ryuichi Yamamoto <notifications@github.com

**Comment by r9y9** [comment]
Trying to find out missing details is fun for me. I'm just trying a lot.

**Comment by hrbigelow** [comment]
Cool!  Yeah, I understand.  By the way, are you the professor at Waseda?  I
have a friend at Ascent robotics doing machine learning and also I lived in
Tokyo last year for three months.

Cheers,

Henry

**Comment by r9y9** [comment]
No. See https://www.linkedin.com/in/zryuichi/?locale=en_US about me.
