### ISSUE TITLE
why use out_channels=10*3?

### ISSUE THREAD

**Issue by rzcwade** [r9y9/wavenet_vocoder#83]
Hi,

Thanks for the amazing work!  I am wondering why you set out_channels to 30 for the case that is not mu-law quantized. Could you give a little more details about "num_mixture * 3 (pi, mean, log_scale)"?

Thanks

**Comment by veqtor** [comment]
Yeah, 3 looks weird, some copy-pasta leftovers from PixelCNN++?

**Comment by bryanjp3** [comment]
It's a mixture distribution. Each component of the distribution is a logistic distribution with a mean, variance, and probability of being selected.

**Comment by r9y9** [comment]
A logistic distribution is parametrized by two parameters: location and scale. For the mixture case we need one more: mixture weight. So num_mixture * 3 (pi, mean, log_scale)" that’s it. I don’t see why you feel it’s weird...

**Comment by rzcwade** [comment]
Thanks for the repose. But how did you calculate training loss based on this output (with 30 channels) ? It seems to me that y (1 channel) and y_hat (30 channels) will have different dimension. 

Thanks

**Comment by rzcwade** [comment]
ah, I saw the implementation of discretized_mix_logistic_loss function. That cleared it out. Thanks again!
