### ISSUE TITLE
Typo! 

### ISSUE THREAD

**Issue by epinar** [r9y9/wavenet_vocoder#86]
https://github.com/r9y9/wavenet_vocoder/blob/1406c9d2f5a3cd86665801101a994a9b98a58a07/train.py#L643

**Comment by r9y9** [comment]
Thanks. Fixed.

**Comment by atreyas313** [comment]
Hi,
thank for publishing wavenet vocoder, I am working on tacotron2 (https://github.com/Rayhane-mamah/Tacotron-2).

I trained network using "python train.py --model='Both' " then tried to synthesis from checkpoints using "python synthesize.py --model='Tacotron-2' " and happen this error:
DataLossError (see above for traceback): file is too short to be an sstable
[[Node: model_1/save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_model_1/save/Const_0_0, model_1/save/RestoreV2/tensor_names, model_1/save/RestoreV2/shape_and_slices)]]
[[Node: model_1/save/RestoreV2/_493 = _Recvclient_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_498_model_1/save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]]

Is it for you possible to guide me which fix this error?

**Comment by nmstoker** [comment]
@atreyas313 - it looks like the issue you describe has no obvious connection with this (closed) issue, so if it's still a problem for you, you should probably open a fresh issue for it. Broadly an issue should be for a single bug/enhancement/request

https://hackernoon.com/45-github-issues-dos-and-donts-dfec9ab4b612
