### ISSUE TITLE
About preprocess

### ISSUE THREAD

**Issue by deli666** [r9y9/wavenet_vocoder#87]
Hi,
I am confused how the training data is generated since the preprocess.py just uses importlib.
To be specific, whether the mel-spectrogram for training is synthesized by pretrained tacotron model or converted from the raw data? If it is generated from raw data, what algorithms do you use?
Best,

**Comment by deli666** [comment]
I assumed that the input training data for this model should be Mels-audio pairs. And the Mels should be synthesized by pretrained tacotron model. However, when I trained your wavenet model, it generates mels and audio pair from LJSpeech dataset directly. Which way is better?

**Comment by m-toman** [comment]
I'm on my phone so please excuse that I don't have the references here: the tacotron paper states that synthesized mels + recordings works better than extracted mels + recordings. This is reasonable as this is what the final system will see.
But in one of the issues here someone stated that with long enough training this wasn't really an issue.

I also fine-tuned the pre-trained models in r9y9s notebook on new data for taco and Wavenet separately and it worked amazingly well after a only a couple hours of training.
At least for a similar speaker.

**Comment by deli666** [comment]
Thank you so much for reply!

**Comment by deli666** [comment]
Thank you so much for reply! 
Best,
