### ISSUE TITLE
is this algorithm the same as nv-wavenet

### ISSUE THREAD

**Issue by suntao2012** [r9y9/wavenet_vocoder#88]
Is this repo algorithm the same as nv-wavenet? https://github.com/NVIDIA/nv-wavenet

**Comment by r9y9** [comment]
I haven't looked into it yet but I guess there's something different in details.

**Comment by suntao2012** [comment]
OK. Because I have looked into the detail of NV-wavenet, it is an implementation of paper https://arxiv.org/abs/1702.07825,
So, could you please tell me which paper is this repo from?

**Comment by r9y9** [comment]
https://github.com/r9y9/wavenet_vocoder#references
