### ISSUE TITLE
Hello, if I want to use your pre-trained wavenet model, what are the specific requirements for the mel spectrogram dimension generated by speech synthesis?

### ISSUE THREAD

**Issue by sunnnnnnnny** [r9y9/wavenet_vocoder#92]

**Comment by gsoul** [comment]
Please kindly see this notebook from the README file of this repo: https://colab.research.google.com/github/r9y9/Colaboratory/blob/master/Tacotron2_and_WaveNet_text_to_speech_demo.ipynb

After you are able to run it, you should be also able to find answers to your questions.

**Comment by sunnnnnnnny** [comment]
i see it.thank u.
