### ISSUE TITLE
Error when cmu_arctic.py tries to import function 'is_raws' from util.py

### ISSUE THREAD

**Issue by 742617000027** [r9y9/wavenet_vocoder#95]
In the preprocessing step, cmu_arctic.py tries to import the function 'is_raws' from wavenet_vocoder/util.py — in util.py, the function in question is called 'is_raw', so an error occurs due to the difference in name. 

cmu_arctic.py:
`from wavenet_vocoder.util import is_mulaw_quantize, is_mulaw, is_raws`

util.py
`def is_raw(s):
    _assert_valid_input_type(s)
    return s == "raw`

**Comment by r9y9** [comment]
Thanks. That's my fault. Fixed.
