### ISSUE TITLE
Thank you for your open source, I noticed that 20180510_mixture_lj_checkpoint_step000320000_ema.json  frame_shift_ms=0 in this file, why should I set this up?

### ISSUE THREAD

**Issue by sunnnnnnnny** [r9y9/wavenet_vocoder#97]
Hope to receive your reply.

**Comment by r9y9** [comment]
Answer: https://github.com/r9y9/wavenet_vocoder/blob/4b438ce9cefda398bd2c1074b8a07f771b44549c/hparams.py#L34-L36

**Comment by sunnnnnnnny** [comment]
@r9y9 In this case, can I think that frame_shift_ms is useless?then，frame shift=256，What is the length of the frame length?
